feat: typescript
jorisBarkema/svelte-burger-menu pull request #4
Opened 2022-09-27 21:04 UTC by 11reed

Read #3 for more information

2022-09-28 13:59 UTC, jorisBarkema requested changes
Thanks for the contribution, I have to say I don't have a lot of experience with typescript and even less with svelte-typescript configuration so I'll mostly trust you on the correctness of that part.

2022-09-28 13:59 UTC, jorisBarkema commented on src/types/DefaultProps.ts
> +export type IDefaultProps = {}
Is this still used anywhere?

2022-09-28 13:59 UTC, jorisBarkema commented on package.json
>    "version": "1.0.5",
This would be breaking change so its needs a major version increase
```suggestion
  "version": "2.0.0",
```

2022-09-29 07:51 UTC, 11reed commented on src/types/DefaultProps.ts
> +export type IDefaultProps = {}
No, it isn't.

2022-09-29 08:19 UTC, 11reed commented on package.json
>    "version": "1.0.5",
Done

2022-10-01 11:42 UTC, jorisBarkema approved these changes

2022-10-01 11:43 UTC, merged